version: "3.8"
services:
  jenkins:
    container_name: jenkins
    build:
      context: ./dockerfile/jenkins
      dockerfile: Dockerfile
    ports:
      - "9090:8080"   # UI
      - "50000:50000" # Agent
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net

  sonarqube:
    container_name: sonarqube
    build:
      context: ./dockerfile/sonarqube
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./data/sonarqube/sonarqube_data:/opt/sonarqube/data
      - ./data/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - ./data/sonarqube/sonarqube_logs:/opt/sonarqube/logs
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    depends_on:
      - postgres
    networks:
      - net

  postgres:
    restart: always
    container_name: postgres
    build:
      context: ./dockerfile/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/postgresql:/var/lib/postgresql
      - ./data/postgres/postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    networks:
      - net

networks:
  net:
    driver: bridge
