version: "3.8"
services:
  jenkins:
    container_name: jenkins
    build:
      context: ./config/jenkins
      dockerfile: Dockerfile
    ports:
      - "9090:8080"   # UI
      - "50000:50000" # Agent
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net

  sonarqube:
    container_name: sonarqube
    build:
      context: ./config/sonarqube
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./data/sonarqube/sonarqube_data:/opt/sonarqube/data
      - ./data/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - ./data/sonarqube/sonarqube_logs:/opt/sonarqube/logs
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    depends_on:
      - postgres
    networks:
      - net

  postgres:
    restart: always
    container_name: postgres
    build:
      context: ./config/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/postgresql:/var/lib/postgresql
      - ./data/postgres/postgresql_data:/var/lib/postgresql/data
      - .config/postgres/init.sql /docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    networks:
      - net

  prometheus:
    restart: always
    container_name: prometheus
    build:
      context: ./config/prometheus
      dockerfile: Dockerfile
    ports:
      - "9091:9090"
    volumes:
      - ./data/prometheus:/opt/bitnami/prometheus/conf
      - ./config/prometheus/prometheus.yaml:/opt/bitnami/prometheus/conf/prometheus.yml
    networks:
      - net

  grafana:
    restart: always
    container_name: grafana
    build:
      context: ./config/grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - net

networks:
  net:
    driver: bridge
