global:
  scrape_interval: "1s"
  evaluation_interval: "1s"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # - alertmanagers: 9093
# rule_files:
#   - "first_rules.yaml"
#   - "second_rules.yaml"

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /prometheus
    static_configs:
      - targets: ["jenkins:8080"]
